### ISSUE TITLE
visual bugs in properties

### ISSUE THREAD

**Issue by KraXen72** [xRyul/obsidian-arcane-theme#1]
![image](https://github.com/xRyul/obsidian-arcane-theme/assets/21956756/f86225cd-bad4-4153-b6ad-cb7f500cc95b)
i tried turning off my snippets and it doesen't affect them. let me know if you need my plugin list, but i don't think i have any that modify the property view.

**Comment by xRyul** [comment]
thanks for reporting! 

I wasn't expecting it to be approved so quickly, no to mention get any users so quickly! I will try to look into it over this weekend!
